[package]
name = "clr_profiler_macros"
version = "0.1.0"
authors = ["Camden Reslink <camdenreslink@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/camdenreslink/clr-profiler"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0.35"
